name: trading_app
description: "AI Trading Analysis App with Camera and 3D UI."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # کتێبخانە نوێیەکان بۆ کامێرا و زیرەکی دەستکرد
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  http: ^1.1.0
  google_generative_ai: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true